type: yolov8_seg
name: yolov8-seg
display_name: YOLOv8-segmentation
model_path: E:/Documents/PrecisionAssembly/models/yolov8-all.onnx
iou_threshold: 0.45
conf_threshold: 0.25
classes:
  - keyhole
  - hole
  - gear
  - calib_hole
